travis:
  secure:
    BINSTAR_TOKEN: sTq81/FAQZZhIKJc9GAkcIk8TZaDhXMfiCpeOfJpd+wfTT2tcb6Dk/pCVLQczDOpY9MKhUlVJsBlqbF/nVNDS+WujMTb/wNfkuTLWQnzLML1fKiG9Rs8q2Tuz/yXaOo+TlsoVlHIZzf8cJGYg5vTHs14i3U215ORtUJrWedZcerd0OIGi2WyTmWxSiXFPNdMpQaKjbt9vIlIAzJpGFs0DGdF6E6e164s9NHpir33GPZayNeTwepJ9/qpLtz8vlhNn9dXlbcRQY8l7lJU9YD4firRB1I1HMJQXxu5ucRdoJlhjtvZqDHGoVRvxo/slTrYpt/Kgmtmjpyb9/CNli7rrvnpzEPZr9Q/6C70ve1uzBFxOXji+1cJIQ25iiCJ70FOptat1z27QgG9V3OU1P120617S45jgCwMa8XiWzcJtsy0SkkDicU81X/MVytzeOecEJWKPK/0j5+wQ70Ypq+wa/ms9rhL8zjHL3x+D15XZag0sd2IxehG4aM7SF0iewDfdpnISF4jf2NQWPl7a+6MSRsjA3n0v42gUV6KzazegTpsGr9SLqFBIq7B2fEXyqSgBApjZKoWwi1Yw5lmwyjuoJx3IXwi3cu3kZfGvv14J+625SsgdrW33EohXYI83CHEFoyiRXUXjhf+qe8vbHIrL6CiLhmN8xuuzoxUGTjZx6c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
